# Generated by Django 2.2.2 on 2019-06-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190613_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carreer',
            new_name='Major',
        ),
    ]
