# Generated by Django 2.2.2 on 2019-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190619_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='carreer_id',
            new_name='major_id',
        ),
    ]
